apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenops

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - apps.yaml
  - frontend.yaml
  - monitoring.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: greenops-platform

configMapGenerator:
  - name: frontend-assets
    files:
      - index.html=../frontend/index.html
  - name: caddy-config
    files:
      - Caddyfile=../docker/caddy/Caddyfile
  - name: prometheus-config
    files:
      - prometheus.yml=../monitoring/prometheus/prometheus.yml
  - name: grafana-datasource
    files:
      - prometheus.yml=../monitoring/grafana/provisioning/datasources/prometheus.yml
  - name: grafana-dashboard-provider
    files:
      - greenops.yml=../monitoring/grafana/provisioning/dashboards/greenops.yml
  - name: grafana-dashboards
    files:
      - greenops-overview.json=../monitoring/grafana/dashboards/greenops-overview.json
