apiVersion: v1
kind: Secret
metadata:
  name: greenops-secrets
  namespace: greenops
type: Opaque
stringData:
  JWT_SECRET: GreenOpsJwtDemo2026u7N9pQ2sV5xL8rT4mK6c
  POSTGRES_PASSWORD: GreenOpsPgDemo2026V7nR4qT9sL2
  GRAFANA_ADMIN_PASSWORD: GreenOpsGrafanaDemo2026Q8mK5pZ1vX
